### ISSUE TITLE
HandTrackingExample.py  

### ISSUE THREAD

**Issue by Vit8692** [RangeOfGlitching/cvzone#1]
`length, info, img = detector.findDistance(lmList1[8], lmList2[8], img)  # with draw`
has an error below
ValueError: too many values to unpack (expected 2)

```
  def findDistance(self, p1, p2, img=None):
      x1, y1 = p1
      x2, y2 = p2
      cx, cy = (x1 + x2) // 2, (y1 + y2) // 2
      length = math.hypot(x2 - x1, y2 - y1)
      info = (x1, y1, x2, y2, cx, cy)
      if img is not None:
          cv2.circle(img, (x1, y1), 15, (255, 0, 255), cv2.FILLED)
          cv2.circle(img, (x2, y2), 15, (255, 0, 255), cv2.FILLED)
          cv2.line(img, (x1, y1), (x2, y2), (255, 0, 255), 3)
          cv2.circle(img, (cx, cy), 15, (255, 0, 255), cv2.FILLED)
          return length, info, img
      else:
          return length, info
```

I think the problem is that the lmList2 and lmList1 have 3 element, respectively.

**Comment by RangeOfGlitching** [comment]
Hello
yes, I think mediapipe has change the return value in august. 
Now I fix the error, Please install the lastest version.

![螢幕擷取畫面 2022-09-29 214135](https://user-images.githubusercontent.com/58881058/193047911-c2c10eae-3352-474d-b3f8-b3c40c7f4aa5.png)
